#!/bin/bash

export NODE_OPTIONS=--max-old-space-size=4096

jupyter labextension install @jupyter-widgets/jupyterlab-manager

# https://github.com/jupyterlab/jupyterlab-toc
jupyter labextension install @jupyterlab/toc

jupyter labextension install @lckr/jupyterlab_variableinspector

# https://github.com/rmotr/jupyterlab-solutions
jupyter labextension install @rmotr/jupyterlab-solutions
jupyter serverextension enable jupyterlab_rmotr_solutions
mv jupyter_notebook_config.py ~/.jupyter/
jupyter labextension install jupyter-matplotlib
jupyter labextension install @ryantam626/jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter

jupyter labextension install jupyter-matplotlib

# https://ipywidgets.readthedocs.io/en/stable/user_install.html
conda install -y -n base -c conda-forge widgetsnbextension
conda install -y -n scientific_programming -c conda-forge ipywidgets

jupyter labextension install jupyterlab_voyager

# Clear output of all notebooks.
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace **/*.ipynb
